### ISSUE TITLE
代码创建会不能实现此效果

### ISSUE THREAD

**Issue by PengSiSi** [iwantFB/iOS_Tool#1]
代码创建会不能实现，最好里面写过initWithFrame初始化吧

- (instancetype)initWithFrame:(CGRect)frame
{
    self = [super initWithFrame:frame];
    if (self) {
        self.keyboardType = UIKeyboardTypeNumberPad;
        self.hideKeyboard = YES;
        
        [self addTarget:self action:@selector(_willbeginEdit) forControlEvents:UIControlEventEditingDidBegin];
        [self addTarget:self action:@selector(_didEndEdit) forControlEvents:UIControlEventEditingDidEnd];
        
        //注册键盘弹起通知
        [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(keyboardWillShow:) name:UIKeyboardWillShowNotification object:nil];
    }
    return self;
}

**Comment by iwantFB** [comment]
谢谢!确实,之前只考虑到了nib的实现,已fix
